### ISSUE TITLE
Ruby Gem has linux and OSX binaries with wrong permissions.

### ISSUE THREAD

**Issue by agitelzon** [svoboda-jan/mozjpeg-ruby#2]
For some reason, the ruby gem at https://rubygems.org/gems/mozjpeg/versions/0.0.2 has the cjpeg binaries with permission 744 (rwxr--r--) instead of 755 (rwxr-xr-x).

This is a problem for us because the user who owns cjpeg is not the one who tries to execute it.

Can you get the ruby gem re-packaged so that the cjpeg binaries have the correct permission?

Thanks,
Alex

**Comment by svoboda-jan** [comment]
I did check the permissions with clean install and git clone, the permissions are `755`. Also there were no reported issues or issues during testing. I would recommend checking the umask configuration for the user or use `sudo` with appropriate configuration.
